# Generated by Django 3.1.7 on 2021-03-03 07:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='destination_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 3, 7, 51, 53, 245773, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 3, 7, 51, 53, 245655, tzinfo=utc)),
        ),
    ]
